package org.fundacionjala.coding.jose;

import java.util.Arrays;
import java.util.Random;

import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

/**
 * Created by JoseTorrez on 9/5/2017.
 */
public class FrequentItemTest {
    private FrequentItem frequentItem;

    /**
     * Initializator.
     */
    @Before
    public void setUp() {
        frequentItem = new FrequentItem();

    }

    /**
     * Basic Test.
     */
    @Test
    public void basicTests() {
        String msg = "Should work with example test cases";
        assertEquals(msg, 2, frequentItem.mostFrequentItemCount(new int[]{3, -1, -1}));
        assertEquals(msg, 5,
                frequentItem.mostFrequentItemCount(new int[]{3, -1, -1, -1, 2, 3, -1, 3, -1, 2, 4, 9, 3}));
    }

    /**
     * Edge Test.
     */
    @Test
    public void edgeTests() {
        assertEquals("Should work for empty arrays", 0,
                frequentItem.mostFrequentItemCount(new int[0]));
        assertEquals("Should work for 1-element arrays", 1,
                frequentItem.mostFrequentItemCount(new int[]{9}));
        assertEquals("Should work with multiple most frequent items, e.g. nine 7's and nine 1's", 3,
                frequentItem.mostFrequentItemCount(new int[]{7, 1, 7, 1, 7, 1}));
    }

    /**
     * Test for numbers generated by random.
     */
    @Test
    public void randomTests() {
        Random randGen = new Random();
        System.out.println("Testing 40 random arrays...");
        for (int i = 0; i < 40; i++) {
            int[] testArr = new int[randGen.nextInt(30)];
            for (int e = 0; e < testArr.length; e++) {
                testArr[e] = randGen.nextInt(30) - 15;
            }
            assertEquals(mostFrequentAns(testArr),
                    frequentItem.mostFrequentItemCount(testArr));
        }
    }

    /**
     * @param collection Integer.
     * @return Integer.
     */
    private int mostFrequentAns(int[] collection) {
        int max = 0;
        int currMax = 0;
        int currNum = 0;
        Arrays.sort(collection);
        for (int i = 0; i < collection.length; i++) {
            if (currNum != collection[i]) {
                if (currMax > max) {
                    max = currMax;
                }
                currMax = 1;
                currNum = collection[i];
            } else {
                currMax++;
            }
        }
        return (currMax > max ? currMax : max);
    }
}
